on: push

permissions:
    contents: write

jobs:
    build0:
        uses: ./.github/workflows/job.yml
    build1:
        needs: build0
        if: ${{!cancelled()}}
        uses: ./.github/workflows/job.yml
    build2:
        needs: build1
        if: ${{!cancelled()}}
        uses: ./.github/workflows/job.yml
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - run: |
              sudo apt update
              sudo apt install -y --no-install-recommends python3-aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
